"""ride offers

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-08 19:48:32.585297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='offerstatus', native_enum=False), server_default='PENDING', nullable=False),
    sa.Column('pickup_distance_m', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_ride_offers_driver_id_drivers')),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], name=op.f('fk_ride_offers_ride_id_rides')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ride_offers')),
    sa.UniqueConstraint('ride_id', 'driver_id', name='uq_ride_offers_ride_id_driver_id')
    )
    op.create_index(op.f('ix_ride_offers_driver_id'), 'ride_offers', ['driver_id'], unique=False)
    op.create_index('ix_ride_offers_status_expires_at', 'ride_offers', ['status', 'expires_at'], unique=False)
    op.create_index('uq_ride_offers_one_pending_per_ride', 'ride_offers', ['ride_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ride_offers_one_pending_per_ride', table_name='ride_offers', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_ride_offers_status_expires_at', table_name='ride_offers')
    op.drop_index(op.f('ix_ride_offers_driver_id'), table_name='ride_offers')
    op.drop_table('ride_offers')
    # ### end Alembic commands ###
