"""safety net unique indexes

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-09 08:03:26.726752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_ride_offers_one_pending_per_driver', 'ride_offers', ['driver_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index('uq_rides_one_active_per_driver', 'rides', ['driver_id'], unique=True, postgresql_where=sa.text("status IN ('DRIVER_ASSIGNED', 'DRIVER_ARRIVED', 'IN_PROGRESS')"))
    op.create_index('uq_rides_one_active_per_rider', 'rides', ['rider_id'], unique=True, postgresql_where=sa.text("status IN ('REQUESTED', 'DRIVER_ASSIGNED', 'DRIVER_ARRIVED', 'IN_PROGRESS')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_rides_one_active_per_rider', table_name='rides', postgresql_where=sa.text("status IN ('REQUESTED', 'DRIVER_ASSIGNED', 'DRIVER_ARRIVED', 'IN_PROGRESS')"))
    op.drop_index('uq_rides_one_active_per_driver', table_name='rides', postgresql_where=sa.text("status IN ('DRIVER_ASSIGNED', 'DRIVER_ARRIVED', 'IN_PROGRESS')"))
    op.drop_index('uq_ride_offers_one_pending_per_driver', table_name='ride_offers', postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###
