"""driver earnings

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-09 17:11:06.303377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride_earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('gross_amount', sa.Integer(), nullable=False),
    sa.Column('commission_percent', sa.Integer(), nullable=False),
    sa.Column('platform_fee', sa.Integer(), nullable=False),
    sa.Column('driver_earning', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('trip', 'cancellation')", name=op.f('ck_ride_earnings_kind_known')),
    sa.CheckConstraint('commission_percent BETWEEN 0 AND 100', name=op.f('ck_ride_earnings_commission_percent_range')),
    sa.CheckConstraint('driver_earning >= 0', name=op.f('ck_ride_earnings_driver_earning_not_negative')),
    sa.CheckConstraint('gross_amount > 0', name=op.f('ck_ride_earnings_gross_positive')),
    sa.CheckConstraint('platform_fee + driver_earning = gross_amount', name=op.f('ck_ride_earnings_split_adds_up')),
    sa.CheckConstraint('platform_fee >= 0', name=op.f('ck_ride_earnings_platform_fee_not_negative')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_ride_earnings_driver_id_drivers')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_ride_earnings_payment_id_payments')),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], name=op.f('fk_ride_earnings_ride_id_rides')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ride_earnings')),
    sa.UniqueConstraint('payment_id', name=op.f('uq_ride_earnings_payment_id')),
    sa.UniqueConstraint('ride_id', name=op.f('uq_ride_earnings_ride_id'))
    )
    op.create_index('ix_ride_earnings_created_at', 'ride_earnings', ['created_at'], unique=False)
    op.create_index('ix_ride_earnings_driver_id_id', 'ride_earnings', ['driver_id', 'id'], unique=False)
    op.add_column('pricing_rules', sa.Column('commission_percent', sa.Integer(), server_default='20', nullable=False))
    # ### end Alembic commands ###
    # Alembic does not detect check constraints on an existing table, so this one is written by hand (full name, as in 0007).
    op.create_check_constraint(op.f('ck_pricing_rules_commission_percent_range'), 'pricing_rules', 'commission_percent BETWEEN 0 AND 100')
    # Every payment made before this milestone (M5.3 and its own backfill included) gets its earning row, split at the
    # commission of the economy rule (20 on a fresh column) and dated like the payment. Rides without a driver or without a
    # trip or cancellation breakdown cannot have a payment, so none is left out on purpose.
    op.execute("""
        INSERT INTO ride_earnings (ride_id, payment_id, driver_id, kind, gross_amount, commission_percent, platform_fee, driver_earning, created_at)
        SELECT p.ride_id, p.id, r.driver_id, r.fare_breakdown->>'kind', p.amount, c.pct,
               (p.amount * c.pct + 50) / 100, p.amount - (p.amount * c.pct + 50) / 100, p.created_at
        FROM payments p
        JOIN rides r ON r.id = p.ride_id
        CROSS JOIN (SELECT commission_percent AS pct FROM pricing_rules WHERE vehicle_type = 'economy') c
        WHERE r.driver_id IS NOT NULL AND r.fare_breakdown->>'kind' IN ('trip', 'cancellation')
    """)
    # Fails the migration loudly, and rolls it back, instead of leaving a payment without its split.
    op.execute("""
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM payments p LEFT JOIN ride_earnings e ON e.payment_id = p.id WHERE e.id IS NULL) THEN
            RAISE EXCEPTION 'payments without earnings after backfill';
          END IF;
        END $$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_pricing_rules_commission_percent_range'), 'pricing_rules', type_='check')
    op.drop_column('pricing_rules', 'commission_percent')
    op.drop_index('ix_ride_earnings_driver_id_id', table_name='ride_earnings')
    op.drop_index('ix_ride_earnings_created_at', table_name='ride_earnings')
    op.drop_table('ride_earnings')
    # ### end Alembic commands ###
