"""ratings

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-10 03:54:06.751653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: Union[str, Sequence[str], None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_summaries',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating_count >= 0', name=op.f('ck_rating_summaries_count_not_negative')),
    sa.CheckConstraint('rating_total BETWEEN rating_count AND rating_count * 5', name=op.f('ck_rating_summaries_total_within_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rating_summaries_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_rating_summaries'))
    )
    op.create_index('ix_ratings_to_user_id_id', 'ratings', ['to_user_id', 'id'], unique=False)
    # ### end Alembic commands ###
    # Alembic does not detect check constraints on an existing table, so these two are written by hand (full names, as in 0009).
    op.create_check_constraint(op.f('ck_ratings_no_self_rating'), 'ratings', 'from_user_id <> to_user_id')
    op.create_check_constraint(op.f('ck_ratings_comment_length'), 'ratings', 'comment IS NULL OR char_length(comment) <= 300')
    # Ratings that exist before this milestone are counted (there are none in a normal database).
    op.execute("""
        INSERT INTO rating_summaries (user_id, rating_count, rating_total, updated_at)
        SELECT to_user_id, count(*), sum(score), now() FROM ratings GROUP BY to_user_id
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_ratings_comment_length'), 'ratings', type_='check')
    op.drop_constraint(op.f('ck_ratings_no_self_rating'), 'ratings', type_='check')
    op.drop_index('ix_ratings_to_user_id_id', table_name='ratings')
    op.drop_table('rating_summaries')
    # ### end Alembic commands ###
