"""pricing rule editor

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-10 04:52:37.934492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, Sequence[str], None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_rule_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('version_before', sa.Integer(), nullable=False),
    sa.Column('version_after', sa.Integer(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version_after = version_before + 1', name=op.f('ck_pricing_rule_changes_version_step')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_pricing_rule_changes_actor_user_id_users')),
    sa.ForeignKeyConstraint(['rule_id'], ['pricing_rules.id'], name=op.f('fk_pricing_rule_changes_rule_id_pricing_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_rule_changes')),
    sa.UniqueConstraint('rule_id', 'version_after', name='uq_pricing_rule_changes_rule_id_version_after')
    )
    op.create_index('ix_pricing_rule_changes_rule_id_id', 'pricing_rule_changes', ['rule_id', 'id'], unique=False)
    op.add_column('pricing_rules', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('pricing_rules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('pricing_rules', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_pricing_rules_updated_by_users'), 'pricing_rules', 'users', ['updated_by'], ['id'])
    op.create_index('ix_ride_offers_created_at', 'ride_offers', ['created_at'], unique=False)
    # ### end Alembic commands ###
    # Alembic does not detect check constraints on an existing table, so these seven are written by hand (full names, as in 0010).
    # No data statement: existing rows get version 1, updated_at now and updated_by NULL from the column defaults.
    op.create_check_constraint(op.f('ck_pricing_rules_base_fare_nonneg'), 'pricing_rules', 'base_fare >= 0')
    op.create_check_constraint(op.f('ck_pricing_rules_per_km_nonneg'), 'pricing_rules', 'per_km >= 0')
    op.create_check_constraint(op.f('ck_pricing_rules_per_min_nonneg'), 'pricing_rules', 'per_min >= 0')
    op.create_check_constraint(op.f('ck_pricing_rules_cancellation_fee_nonneg'), 'pricing_rules', 'cancellation_fee >= 0')
    op.create_check_constraint(op.f('ck_pricing_rules_free_cancel_seconds_nonneg'), 'pricing_rules', 'free_cancel_seconds >= 0')
    op.create_check_constraint(op.f('ck_pricing_rules_min_fare_floor'), 'pricing_rules', 'min_fare >= 100')
    op.create_check_constraint(op.f('ck_pricing_rules_surge_cap_range'), 'pricing_rules', 'surge_cap BETWEEN 1.0 AND 2.0')


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f('ck_pricing_rules_surge_cap_range'), 'pricing_rules', type_='check')
    op.drop_constraint(op.f('ck_pricing_rules_min_fare_floor'), 'pricing_rules', type_='check')
    op.drop_constraint(op.f('ck_pricing_rules_free_cancel_seconds_nonneg'), 'pricing_rules', type_='check')
    op.drop_constraint(op.f('ck_pricing_rules_cancellation_fee_nonneg'), 'pricing_rules', type_='check')
    op.drop_constraint(op.f('ck_pricing_rules_per_min_nonneg'), 'pricing_rules', type_='check')
    op.drop_constraint(op.f('ck_pricing_rules_per_km_nonneg'), 'pricing_rules', type_='check')
    op.drop_constraint(op.f('ck_pricing_rules_base_fare_nonneg'), 'pricing_rules', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ride_offers_created_at', table_name='ride_offers')
    op.drop_constraint(op.f('fk_pricing_rules_updated_by_users'), 'pricing_rules', type_='foreignkey')
    op.drop_column('pricing_rules', 'updated_by')
    op.drop_column('pricing_rules', 'updated_at')
    op.drop_column('pricing_rules', 'version')
    op.drop_index('ix_pricing_rule_changes_rule_id_id', table_name='pricing_rule_changes')
    op.drop_table('pricing_rule_changes')
    # ### end Alembic commands ###
