"""saved places

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-10 08:56:03.738701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0012'
down_revision: Union[str, Sequence[str], None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(address) BETWEEN 1 AND 200', name=op.f('ck_saved_places_address_length')),
    sa.CheckConstraint('char_length(label) BETWEEN 1 AND 30', name=op.f('ck_saved_places_label_length')),
    sa.CheckConstraint('lat BETWEEN -90 AND 90', name=op.f('ck_saved_places_lat_range')),
    sa.CheckConstraint('lng BETWEEN -180 AND 180', name=op.f('ck_saved_places_lng_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_places_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_places'))
    )
    op.create_index('ix_saved_places_user_id_id', 'saved_places', ['user_id', 'id'], unique=False)
    op.create_index('uq_saved_places_user_id_lower_label', 'saved_places', ['user_id', sa.literal_column('lower(label)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_saved_places_user_id_lower_label', table_name='saved_places')
    op.drop_index('ix_saved_places_user_id_id', table_name='saved_places')
    op.drop_table('saved_places')
    # ### end Alembic commands ###
